POST http://localhost:4004/odata/v4/say/sum HTTP/1.1
content-type: application/json

{
    "a": 510,
    "b": 256
}

###

POST http://localhost:4004/odata/v4/say/hello HTTP/1.1
content-type: application/json

{
  "to": "Lucas"
}

###

GET http://localhost:4004/odata/v4/luck/randomLuck
###