POST http://localhost:4004/odata/v4/say/sum
content-type: application/json

{
    "a": 510,
    "b": 256
}

###

POST http://localhost:4004/odata/v4/say/hello
content-type: application/json

{
  "to": ""
}

###

GET http://localhost:4004/odata/v4/luck/randomLuck
###